### ISSUE TITLE
Standards compliant README.md as the one in the example, is in place

### ISSUE THREAD

**Issue by anfibiacreativa** [Azure-Samples/agent-openai-python-prompty#26]
- Consider reducing the overall length and adding a table of contents.

- Some prerequisites are in place about software installs being required, that could be clearer with links back to the documentation and necessary commands, and instructions. (like Terraform or Docker)

- In the prerequisites there is a mix of software to install that is required to build or run the app and deployment configuration recommendations. For example, the region

- Some of the more complex instructions may be better linked to official docs than fully described in the repo, for the sake of brevity, like the python installation instructions. Please refer to this sample for guidance https://github.com/Azure-Samples/azure-search-openai-demo [Azure-Samples/azure-search-openai-demo: A sample app for the Retrieval-Augmented Generation pattern running in Azure, using Azure AI Search for retrieval and Azure OpenAI large language models to power ChatGPT-style and Q&A experiences. (github.com)](https://github.com/Azure-Samples/azure-search-openai-demo)

- Please review points:
https://github.com/Azure-Samples/agent-openai-python-prompty?tab=readme-ov-file#223-provision-and-deploy 
Seems that some of the tasks described are not really performed by the script but `azd up` mechanisms.

- Please consider replacing <--- GUID ---> with <GITHUB_USER_ID> or something more descriptive, or adding more context for accessibility.

**Comment by marlenezw** [comment]
Hi @anfibiacreativa I made some changes to both repos I'm working on based on these suggestions and talking to Cassie. I haven't had time to test end with just azd up, so will test and then see if I can make the app better so people can see what it does.

**Comment by marlenezw** [comment]
I tried to address all of these issues so closing for now
