### ISSUE TITLE
Error with provisioning

### ISSUE THREAD

**Issue by pamelafox** [Azure-Samples/agent-openai-python-prompty#46]
In Desktop Codespaces, I got this error while running azd up, EastUS2:

╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."
│ 
│   with azurerm_role_assignment.aisearchdata_user[0],
│   on rbac.tf line 26, in resource "azurerm_role_assignment" "aisearchdata_user":
│   26: resource "azurerm_role_assignment" "aisearchdata_user" {
│ 
╵

ERROR: error executing step command 'provision': deployment failed: failing invoking action 'provision', error deploying infrastructure: template Deploy failed:  , err:failed running terraform apply:  (exit code: 1)
TraceID: f33ced5f99c23d7faa71d9b3a53054f7

**Comment by pamelafox** [comment]
Maybe this line needs to be user ID? https://github.com/Azure-Samples/agent-openai-python-prompty/blob/main/infra/rbac.tf#L28

**Comment by marlenezw** [comment]
I think this helped Andre solve the issue! Thank you @pamelafox! I'd love for you to test it again to see if it's working now for you and then I'll close
