### ISSUE TITLE
Leverage MSI for OpenAI Access

### ISSUE THREAD

**Issue by codebytes** [Azure-Samples/agent-openai-python-prompty#6]
AZD Terraform template is using OpenAI Keys 
Leverage MSI if possible

**Comment by codebytes** [comment]
Still seeing keys

**Comment by codebytes** [comment]
still not working with keys

**Comment by andredewes** [comment]
Give yourself "Cognitive Services OpenAI User" permission in the target OpenAI resource.

**Comment by pamelafox** [comment]
Typically those sort of roles are assigned in the IAC, is that not possible for this one?

**Comment by andredewes** [comment]
Yes, but you need to run "azd up" first to assign those. This repo is still not ready with that, so the test locally the app the only possibility is to manually assign yourself that role.

**Comment by pamelafox** [comment]
Ah okay, could you provide a scrip then? https://github.com/Azure-Samples/rag-postgres-openai-python/blob/main/scripts/setup_openai_role.sh
Could make it slightly easier?

**Comment by anfibiacreativa** [comment]
Can you please reopen until either myself, @kristenwomack or @codebytes have tested. Thank you!
